version: '2'

services:
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  concourse-web:
    image: concourse/concourse:5.0.0
    command: web
    links: [concourse-db]
    depends_on: [concourse-db]
    ports: ["8080:8080"] # EDIT if necessary
    volumes: ["./keys/web:/concourse-keys"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=http://10.173.61.53:8080 #CHANGE_ME
    - CONCOURSE_ADD_LOCAL_USER=pks:vmware
    #- CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true
    #- CONCOURSE_GARDEN_DNS_PROXY_ENABLE=true
    #- CONCOURSE_WORKER_GARDEN_DNS_PROXY_ENABLE=true
    #- CONCOURSE_VAULT_URL=http://10.173.61.53:8200
    #- CONCOURSE_VAULT_CLIENT_TOKEN=s.PMpOdgvashIxZrzSZVwJ4aht
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=pks

  concourse-worker:
    image: concourse/concourse:5.0.0
    command: worker
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    volumes:
    - "./keys/worker:/concourse-keys"
    environment:
    - CONCOURSE_TSA_HOST=concourse-web:2222
    - CONCOURSE_GARDEN_NETWORK
    - CONCOURSE_GARDEN_DNS_SERVER=10.173.61.54

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
    - /downloads/:/var/www/html/
    #- ./nginx/conf.d:/etc/nginx/conf.d
    #- ./nginx/vhost.d:/etc/nginx/vhost.d
    - /downloads/:/usr/share/nginx/html
    #- ./nginx/certs:/etc/nginx/certs:ro
    #- ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
    ports:
    - "80:80"
    - "443:443"

